### PR TITLE
Autoauto Static Linking

### PR DESCRIPTION
**Pull request by chlohal**
# AA Static Linking

This PR adds static linking and static analysis to the Autoauto compiler; it also includes the broad refactoring required to do so. Benefits are itemized below.

CC @Mario-Runner , @achyutS1281

## Why?

Static linking means that instead of checking for dependencies at runtime, the *compiler* checks for dependencies. This lets it catch problems earlier.

Since the compiler is in charge of putting dependencies together, it can also do type checking (e.g. "oh, are you subtracting a string? that's bad") across every compile unit.

This *is* a separation from the approach I had last year ("if you mess up, then it'll let you"), but not as much as it might seem. The runtime will still let you do whatever you want! The compiler is just now smart enough to warn you beforehand when you're doing something odd. 

### Compile/Build Performance
- Improved performance on low-spec laptops
- Mildly improved perfomance on high-spec computers (multi-threading)
- Allow multithreading with dependencies across multiple files
- Replace PEG.js Autoauto parser with hand-written Pratt parser (~3x speedup)
- `use strict` mode on all Javascript code
- Use V8 serialize/deserialize for caches
- Cleaned up `build.gradle`

### Runtime Performance
- Make indexed jumps **absolute** instead of relative
- Remove runtime dependency resolver (which used reflection :/ )
- Make bytecode compiler default
- Static optimizer improvements 

## Maintainability

- Added type annotations to Javascript code; this allows for Intellisense in VS Code
- Rewrote much of the compiler structure to be easily understood
- Consolidated all bytecode-related manifests into single copies
- Rewrote the type checker entirely 
- Require a *different* `compilerMode` for dependencies like `pid-turn.autoauto` (enforces different thought process; better for eventual collisions)

## User Utility

- Added 20+ new warning messages
	- Missing dependency
	- Undefined variable
	- Calling a non-function
	- Recursive datatypes
	- `goto` to a nonexistent path
	- Use opmode as a library
	- Circular dependency
	- Improper algebra (e.g. dividing a function, adding a function, etc etc)
	- Getting property of non-table (e.g. `2.something`)
	- Getting unknown property (e.g. `Math.thisIsntAMathFunction`)
	- Conflicting abbreviations (e.g. "mil" being nautical miles / normal miles)
	- Report error when caches are corrupted
	- Report error when the disk is full
	- Hint for function arguments
	- Detect typos for misinterpretation of frontmatter hints
- Maintained "duck typing": user doesn't have to worry about writing types; the compiler will figure it out for them.
- Added coloured warning messages and error messages, with code previews for context
- Added summary of warnings, errors, and time spent compiling
- Made *many* features optional, with easy toggles in `build.gradle`
	- Making tests
	- Build history
	- AGPBI messages (highly recommended for Android Studio)
	- ANSI Colour (on by default)
	- ASCII/Unicode rendering of details (on by default)

### CODE REVIEW

**Comment by Mario-Runner** [comment]
So this will increase the efficiency of autoauto and also make it easier to use for beginners, since it gives more error responses when given incorrect commands?

**Comment by chlohal** [comment]
Yep, exactly!! It's not done atm, but it should be in a good shape for merging soon. I want to make a ton of tests and verify that there aren't any bugs, and then I'll re-request you as a reviewer & you can examine before merging it

**Comment by Mario-Runner** [comment]
Alright, sounds great. Thanks for this help even though you've graduated already :)

**Comment by chlohal** [comment]
Oh! no problem-- Autoauto is a hobby project for me at this point, haha :)

**Comment by chlohal** [comment]
Finished! Passes all autoauto-based tests. Pinging @Mario-Runner @achyutS1281 for review

**Comment by achyutS1281** [comment]
Great! Thx so much for working on this beyond the grave! One Q: What kinds of errors, if any, can this not predict?

**Comment by chlohal** [comment]
good question. The type checker, which powers most of the analysis, doesn't like **recursive data**. For example:

```js
let i = 3, next;
let i = i + 1, next;
skip -1;
```

This can cause problems because `i` depends on `i` in a loop. Simple cases like the counter are handled with a flat-pooler, but (for example) a function that calls itself or putting a table inside itself (e.g. `let Math.math = Math`) is... iffy, to say the least. 

Recursive data which the checker can't flat-pool will result in a warning.

This is all due to deficiencies in the type checker, specifically, that it can't resolve generics (`?` types, that start as "anything" and then need to be constrained as the checker goes on). It just poops out if it finds something that would need generics.

Also, when functions are passed around between files, it may complain. Especially when functions are nested, it's... not the best developer experience.

Another error is bad function calling. Something like `driveOmni("pigs!")` wouldn't get warned; that's simply an issue from me running out of time. This is also linked to the generics: a fully accurate function-calling checker would need them. I had planned to put a simple checker in place, but sadly it's more complex than I'd thought.

The absence of function-call checking is the single biggest gaping hole in the checks.

**Review by Mario-Runner — APPROVED** [review]
Looks good, seems to be adding new files for functions, changing old files to ensure their new functionality, and then removing files that are no longer of use. Sorry this took a bit to review, I've been busy over the last few meetings.

**Comment by chlohal** [comment]
>  Sorry this took a bit to review, I've been busy over the last few meetings.

no worries! i've been busy too :/

**Comment by achyutS1281** [comment]
I agree with Connor... I don't see any errors this might have. How do I accept the pull req or is it already accepted?

**Comment by chlohal** [comment]
To accept, you can click the "Merge Pull Request" button. That will add all the commits into the master branch, but there aren't any conflicts, so it should be a simple `git pull` for people to download the changes :)

**Pull request merged**
